services:
  web:
    image: node:lts
    working_dir: /app
    volumes:
      - ./src:/app/src
      - ./package.json:/app/package.json
      - ./tsconfig.json:/app/tsconfig.json
      - ./public:/app/public
      - ./docs:/app/docs
    ports:
      - 3000
    labels:
      - "traefik.http.routers.stephaniekolmerienny.rule=Host(`stephaniekolmerienny.localhost`)"
      - "traefik.http.services.stephaniekolmerienny.loadbalancer.server.port=3000"
    networks:
      - web
    command: sh -c "npm install && npm start"

networks:
  web:
    external: true
